[package]
name = "common-eth"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
test = false

[dependencies]
# Workspace dependencies

anyhow = "1"
hex = "0.4"
web3 = "0.18.0"

[dev-dependencies]
